import type { Event } from "@/types/event";
import eventCover from "@/assets/image 5.png"

export const events: Event[] = [
  {
    _id: "1",
    eventTitle: "Lagos Frontend Meetup",
    eventNumber: "0001",
    category: "TECH",
    coverImage: eventCover,
    date: "2026-02-14",
    EventType: "Free",
    sold: 312,
    capacity: 500,
    revenue: null,
    status: "Live",
  },
  {
    _id: "2",
    eventTitle: "Afrobeats Night Market",
    eventNumber: "0001",
    category: "Concert",
    coverImage: eventCover,
    date: "2026-02-14",
    EventType: "Paid",
    sold: 312,
    capacity: 500,
    revenue: 2080000,
    status: "Live",
  },
  {
    _id: "3",
    eventTitle: "Afrobeats Night Market",
    eventNumber: "0001",
    category: "Concert",
    coverImage: eventCover,
    date: null,
    EventType: "Paid",
    sold: null,
    capacity: null,
    revenue: null,
    status: "Draft",
  },
  {
    _id: "4",
    eventTitle: "Afrobeats Night Market",
    eventNumber: "0001",
    category: "CONCERT",
    coverImage: eventCover,
    date: "2026-02-14",
    EventType: "Free",
    sold: 62,
    capacity: 500,
    revenue: 10000000,
    status: "Sold out",
  },
  {
    _id: "5",
    eventTitle: "Afrobeats Night Market",
    eventNumber: "0001",
    category: "Concert",
    coverImage: eventCover,
    date: "2026-02-14",
    EventType: "Paid",
    sold: 500,
    capacity: 500,
    revenue: 4680000,
    status: "Past",
  },
  {
    _id: "6",
    eventTitle: "Afrobeats Night Market",
    eventNumber: "0001",
    category: "Concert",
    coverImage: eventCover,
    date: null,
    EventType: "Free",
    sold: null,
    capacity: null,
    revenue: null,
    status: "Draft",
  },
  {
    _id: "7",
    eventTitle: "Crypto Riches Seminar",
    eventNumber: "0001",
    category: "Conference",
    coverImage: eventCover,
    date: "2026-02-14",
    EventType: "Paid",
    sold: null,
    capacity: null,
    revenue: null,
    status: "Rejected"
  },
];
