import type { Attendee } from "@/types/attendees";

export const attendees: Attendee[] = [
  // Afrobeats Night Market (eventId: "2")
  {
    _id: "a1",
    eventId: "2",
    name: "Ada Okafor",
    email: "ada@gmail.com",
    ticketType: "VIP",
    tableSize: null,
    referenceCode: "EVT-8FQ2",
    purchasedDate: "2026-02-02",
    checkedIn: true,
  },
  {
    _id: "a2",
    eventId: "2",
    name: "Tunde Bello",
    email: "tunde@gmail.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-1A26",
    purchasedDate: "2026-02-03",
    checkedIn: true,
  },
  {
    _id: "a3",
    eventId: "2",
    name: "Chioma Eze",
    email: "chioma@gmail.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-77KP",
    purchasedDate: "2026-02-03",
    checkedIn: true,
  },
  {
    _id: "a4",
    eventId: "2",
    name: "Musa Ibrahim",
    email: "musa@gmail.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-SQW1",
    purchasedDate: "2026-02-04",
    checkedIn: false,
  },
  {
    _id: "a5",
    eventId: "2",
    name: "Zainab Yusuf",
    email: "zainab@gmailcom",
    ticketType: "VIP",
    tableSize: null,
    referenceCode: "EVT-33RT",
    purchasedDate: "2026-02-05",
    checkedIn: false,
  },
  {
    _id: "a6",
    eventId: "2",
    name: "Emeka Obi",
    email: "emeka@gmail.com",
    ticketType: "Table",
    tableSize: 5,
    referenceCode: "EVT-TBL5",
    purchasedDate: "2026-02-06",
    checkedIn: false,
  },
  {
    _id: "a7",
    eventId: "2",
    name: "Fola Adeyemi",
    email: "fol@gmail.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-5510",
    purchasedDate: "2026-02-06",
    checkedIn: false,
  },
  {
    _id: "a8",
    eventId: "2",
    name: "Grace John",
    email: "grace@gmail.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-6620",
    purchasedDate: "2026-02-07",
    checkedIn: false,
  },

  // Lagos Frontend Meetup (eventId: "1")
  {
    _id: "a9",
    eventId: "1",
    name: "Dayo Fashola",
    email: "dayo.fashola@example.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-5HK2",
    purchasedDate: "2026-02-10",
    checkedIn: true,
  },
  {
    _id: "a10",
    eventId: "1",
    name: "Ngozi Chukwu",
    email: "ngozi.chukwu@example.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-8VB6",
    purchasedDate: "2026-02-11",
    checkedIn: true,
  },
  {
    _id: "a11",
    eventId: "1",
    name: "Kelechi Uzo",
    email: "kelechi.uzo@example.com",
    ticketType: "Regular",
    tableSize: null,
    referenceCode: "EVT-3JD0",
    purchasedDate: "2026-02-12",
    checkedIn: false,
  },
];