import type { Ticket} from "@/types/ticket"

export const tickets: Ticket[] = [
  {
    id: "1",
    category: "Concert · Afrobeats",
    title: "Afrobeats Night Market",
    status: "Regular",
    // date: "Sat 14 Feb",
    // time: "6:00 PM",
     eventDateTime:"2026-08-15T18:00:00.000Z",
    entryPoint: "Gate B",
    venue: "Muri Okunola Park, VI · Ada Okafor",
    ticketId: "0001",
    referenceCode: "EVT-8FQ2",
    holderName: "Ada Okafor",
    admits: "Admit 1",
    qrImageUrl: "https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=TICKET-0001-EVT-8FQ2",
    // transferable: false,
    refundPolicy: {
      type: "refundable",
      note: "Refunds allowed until 3 days before the event.",
    },
  },
   {
     id: "2",
    category: "Party",
    title: "Amapiano All Night",
    status: "VIP",
    // date: "Sat 21 Feb",
    // time: "10:00 PM",
    eventDateTime:"2026-08-15T18:00:00.000Z",
    entryPoint: "Main entrance",
    venue: "Hard Rock Cafe, VI · Ada Okafor",
    ticketId: "0001",
    referenceCode: "EVT-8FQ2",
    holderName: "Ada Okafor",
    admits: "Admit 1",
    qrImageUrl: "https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=TICKET-0002-EVT-8FQ2",
    // transferable: false,
    refundPolicy: {
      type: "non-refundable",
      note: "Non-refundable",
    },
   },
   {
     id: "3",
    category: "Tech · Meetup",
    title: "Lagos Frontend Meetup",
    status: "Free",
    // date: "Thr 26 Feb",
    // time: "5:30 PM",
     eventDateTime: "2026-08-15T18:00:00.000Z",
    entryPoint: "Reception",
    venue: "Zone Tech Park, Yaba · Ada Okafor",
    ticketId: "0001",
    referenceCode: "EVT-8FQ2",
    holderName: "Ada Okafor",
    admits: "Admit 1",
    qrImageUrl: "https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=TICKET-0003-EVT-8FQ2",
    // transferable: false,
    refundPolicy: {
      type: "free-cancel",
      note: "Free event - cancel anytime to release your spot.",
    },
   }
]