import { useQuery } from '@tanstack/react-query';
import type { OrganizerEventDetails } from '@/types/organizer-event';

// Sample dynamic event presets reflecting real backend responses
export const MOCK_ORGANIZER_EVENTS: Record<string, OrganizerEventDetails> = {
  '1': {
    id: '1',
    slug: 'lagos-frontend-meetup',
    title: 'Lagos Frontend Meetup',
    eventNumber: 'No 0001',
    category: 'Concert',
    status: 'LIVE',
    paymentType: 'FREE',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
    dateText: 'Thursday 12 feb.',
    venueText: 'Zone Tech Park Yaba',
    isAccountUnderReview: true,
    metrics: {
      ticketsSold: 312,
      totalTickets: 500,
      revenue: 1000000,
      remainingTickets: 118,
      checkedInCount: 0,
    },
    ticketTypes: [
      {
        id: 'tt-1',
        name: 'GENERAL ADMISSION (RSVP)',
        price: 0,
        slug: 'general-admission-rsvp',
        sold: 312,
        left: 118,
      },
    ],
    recentAttendees: [
      {
        id: 'att-1',
        slug: 'att-1',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'IN',
      },
      {
        id: 'att-2',
        slug: 'att-2',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
      {
        id: 'att-3',
        slug: 'att-3',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
    ],
    isPromoted: false,
    promotionMessage: 'This event is not promoted yet. Boost it for a featured spot on homepage and explore',
  },
  '2': {
    id: '2',
    slug: 'afrobeats-night-market',
    title: 'Afrobeats Night Market',
    eventNumber: 'No 0001',
    category: 'Party',
    status: 'SOLD OUT',
    paymentType: 'PAID',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop',
    dateText: 'Thursday 12 feb.',
    venueText: 'Zone Tech Park Yaba',
    isAccountUnderReview: true,
    metrics: {
      ticketsSold: 500,
      totalTickets: 500,
      revenue: 10000000,
      remainingTickets: 0,
      checkedInCount: 0,
    },
    ticketTypes: [
      {
        id: 'tt-1',
        name: 'REGULAR',
        price: 15000,
        slug: 'regular',
        sold: 400,
        left: 0,
      },
      {
        id: 'tt-2',
        name: 'VIP',
        price: 35000,
        slug: 'vip',
        sold: 100,
        left: null,
      },
    ],
    recentAttendees: [
      {
        id: 'att-1',
        slug: 'att-1',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'IN',
      },
      {
        id: 'att-2',
        slug: 'att-2',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
      {
        id: 'att-3',
        slug: 'att-3',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
    ],
    isPromoted: false,
    promotionMessage: 'This event is not promoted yet. Boost it for a featured spot on homepage and explore',
  },
  '3': {
    id: '3',
    slug: 'crypto-riches-seminar',
    title: 'Crypto Riches Seminar',
    eventNumber: 'No 0001',
    category: 'Conference',
    status: 'REJECTED',
    paymentType: 'PAID',
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    dateText: 'Thursday 12 feb.',
    venueText: 'Zone Tech Park Yaba',
    isAccountUnderReview: true,
    metrics: {
      ticketsSold: null,
      totalTickets: null,
      revenue: null,
      remainingTickets: null,
      checkedInCount: 0,
    },
    ticketTypes: [
      {
        id: 'tt-1',
        name: 'REGULAR',
        price: 15000,
        slug: 'regular',
        sold: 0,
        left: null,
      },
      {
        id: 'tt-2',
        name: 'VIP',
        price: 35000,
        slug: 'vip',
        sold: 0,
        left: null,
      },
    ],
    recentAttendees: [
      {
        id: 'att-1',
        slug: 'att-1',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'IN',
      },
      {
        id: 'att-2',
        slug: 'att-2',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
      {
        id: 'att-3',
        slug: 'att-3',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
    ],
    isPromoted: false,
    promotionMessage: 'This event is not promoted yet. Boost it for a featured spot on homepage and explore',
  },
  '4': {
    id: '4',
    slug: 'tech-summit-lagos',
    title: 'Tech Summit Lagos',
    eventNumber: 'No 0004',
    category: 'Conference',
    status: 'LIVE',
    paymentType: 'PAID',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
    dateText: 'Friday 20 Mar.',
    venueText: 'Eko Hotels & Suites, Victoria Island',
    isAccountUnderReview: true,
    metrics: {
      ticketsSold: 400,
      totalTickets: 500,
      revenue: 4680000,
      remainingTickets: 100,
      checkedInCount: 0,
    },
    ticketTypes: [
      {
        id: 'tt-1',
        name: 'REGULAR',
        price: 15000,
        slug: 'regular',
        sold: 250,
        left: 150,
      },
      {
        id: 'tt-2',
        name: 'VIP',
        price: 35000,
        slug: 'vip',
        sold: 250,
        left: null,
      },
    ],
    recentAttendees: [
      {
        id: 'att-1',
        slug: 'att-1',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'IN',
      },
      {
        id: 'att-2',
        slug: 'att-2',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
      {
        id: 'att-3',
        slug: 'att-3',
        name: 'Ada Okafor',
        avatarInitials: 'AO',
        tier: 'VIP',
        referenceCode: 'EVT-8FQ2',
        status: 'GOING',
      },
    ],
    isPromoted: false,
    promotionMessage: 'This event is not promoted yet. Boost it for a featured spot on homepage and explore',
  },
};

export function useOrganizerEventDetails(eventId?: string) {
  const targetId = eventId || '1';
  return useQuery({
    queryKey: ['organizer-event-details', targetId],
    queryFn: async (): Promise<OrganizerEventDetails> => {
      // Simulate API network latency
      await new Promise((resolve) => setTimeout(resolve, 150));
      return MOCK_ORGANIZER_EVENTS[targetId] || MOCK_ORGANIZER_EVENTS['1'];
    },
  });
}
