import type { AdminEvent } from './admin-event';
import { UI_ASSETS } from '@/lib/assets';

export const MOCK_ADMIN_EVENTS: AdminEvent[] = [
  {
    id: 'evt-1',
    title: 'Afrobeats Night Market',
    slug: 'afrobeats-night-market',
    organizerName: 'Lagos Live Co.',
    organizerInitials: 'AN',
    type: 'PAID',
    soldText: '312/500',
    soldCount: 312,
    totalCapacity: 500,
    status: 'LIVE',
    totalCheckedIn: 3,
    totalNotIn: 5,
    details: {
      category: 'CONCERT',
      description:
        'Organizer-provided description. Afrobeats Night Market is presented by Lagos Live Co. This is the full write-up attendees will see on the public event pae. including what to expect, line-up and entry details.',
      formattedDate: 'Sat 14 Feb - 6:00 PM',
      venue: 'Muri Okunola Park, Lagos',
      capacity: 400,
      agePolicy: '18+',
      refundPolicy: 'Refunds until 3 days before',
      bannerImage: UI_ASSETS.manWithHandup,
      organizer: {
        id: 'org-1',
        name: 'Lagos Live Co.',
        initials: 'LL',
        verified: true,
      },
      ticketTypes: [
        {
          id: 't-1',
          name: 'Regular',
          price: 15000,
          quantity: 300,
        },
        {
          id: 't-2',
          name: 'VIP',
          price: 35000,
          quantity: 100,
        },
      ],
    },
  },
  {
    id: 'evt-2',
    title: 'Lagos Wine & Jazz Night',
    slug: 'lagos-wine-jazz-night',
    organizerName: 'PartyVerse NG.',
    organizerInitials: 'LW',
    type: 'PAID',
    soldText: '-',
    status: 'PENDING',
    details: {
      category: 'MUSIC & DRINKS',
      description: 'An evening of fine wine tasting, smooth live jazz performances, and networking with wine enthusiasts.',
      formattedDate: 'Fri 20 Mar - 7:00 PM',
      venue: 'Eko Hotel & Suites, Victoria Island',
      capacity: 250,
      agePolicy: '21+',
      refundPolicy: 'No refunds',
      bannerImage:
        'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-2',
        name: 'PartyVerse NG.',
        initials: 'PV',
        verified: true,
      },
      ticketTypes: [
        { id: 't-3', name: 'Single Entry', price: 25000, quantity: 200 },
        { id: 't-4', name: 'Couple Ticket', price: 45000, quantity: 50 },
      ],
    },
  },
  {
    id: 'evt-3',
    title: 'Detty December Boat Party',
    slug: 'detty-december-boat-party',
    organizerName: 'PartyVerse NG',
    organizerInitials: 'DO',
    type: 'PAID',
    soldText: '500/500',
    soldCount: 500,
    totalCapacity: 500,
    status: 'LIVE',
    details: {
      category: 'PARTY',
      description: 'The ultimate boat cruise experience featuring top DJs, unlimited drinks, and scenic views of Lagos lagoon.',
      formattedDate: 'Sun 27 Dec - 4:00 PM',
      venue: 'Lekki Phase 1 Jetty',
      capacity: 500,
      agePolicy: '18+',
      refundPolicy: 'Refunds up to 7 days before',
      bannerImage:
        'https://images.unsplash.com/photo-1533174072545-7a4ce6ad2a58?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-2',
        name: 'PartyVerse NG',
        initials: 'PV',
        verified: true,
      },
      ticketTypes: [
        { id: 't-5', name: 'Deck Pass', price: 30000, quantity: 400 },
        { id: 't-6', name: 'VVIP Lounge', price: 75000, quantity: 100 },
      ],
    },
  },
  {
    id: 'evt-4',
    title: 'Get Rich Crypto Seminar',
    slug: 'get-rich-crypto-seminar',
    organizerName: 'Unknown Ltd',
    organizerInitials: 'GR',
    type: 'PAID',
    soldText: '8/1000',
    soldCount: 8,
    totalCapacity: 1000,
    status: 'FLAGGED',
    details: {
      category: 'FINANCE',
      description: 'High-yield trading secrets and guaranteed crypto returns masterclass.',
      formattedDate: 'Sat 10 Apr - 10:00 AM',
      venue: 'Online / Zoom Webcast',
      capacity: 1000,
      agePolicy: 'None',
      refundPolicy: 'No refunds',
      bannerImage:
        'https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-3',
        name: 'Unknown Ltd',
        initials: 'UL',
        verified: false,
      },
      ticketTypes: [
        { id: 't-7', name: 'Access Ticket', price: 50000, quantity: 1000 },
      ],
    },
  },
  {
    id: 'evt-5',
    title: 'Yaba Tech Job Fair',
    slug: 'yaba-tech-job-fair',
    organizerName: 'Tx Africa Events.',
    organizerInitials: 'YT',
    type: 'FREE',
    soldText: '-',
    status: 'PENDING',
    details: {
      category: 'CAREER',
      description: 'Connect top tech talents with fast-growing African startups, tech hubs, and venture firms.',
      formattedDate: 'Thu 15 May - 9:00 AM',
      venue: 'Yaba College of Technology Auditorium',
      capacity: 1200,
      agePolicy: 'Open to all',
      refundPolicy: 'Free event',
      bannerImage:
        'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-4',
        name: 'Tx Africa Events.',
        initials: 'TX',
        verified: true,
      },
      ticketTypes: [
        { id: 't-8', name: 'General Entry (Free)', price: 0, quantity: 1200 },
      ],
    },
  },
  {
    id: 'evt-6',
    title: 'Comedy Central Live',
    slug: 'comedy-central-live',
    organizerName: 'Naija Comedy Co.',
    organizerInitials: 'CC',
    type: 'PAID',
    soldText: '180/180',
    soldCount: 180,
    totalCapacity: 180,
    status: 'PAST',
    details: {
      category: 'COMEDY',
      description: 'A night of non-stop laughter with Nigeria’s funniest stand-up comedians.',
      formattedDate: 'Sun 10 Jan - 6:00 PM',
      venue: 'Terra Kulture, Victoria Island',
      capacity: 180,
      agePolicy: '16+',
      refundPolicy: 'No refunds',
      bannerImage:
        'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-5',
        name: 'Naija Comedy Co.',
        initials: 'NC',
        verified: true,
      },
      ticketTypes: [
        { id: 't-9', name: 'Standard', price: 10000, quantity: 150 },
        { id: 't-10', name: 'Front Row', price: 20000, quantity: 30 },
      ],
    },
  },
  {
    id: 'evt-7',
    title: 'Miracle Money Workshop',
    slug: 'miracle-money-workshop',
    organizerName: 'Faith Global',
    organizerInitials: 'MM',
    type: 'PAID',
    soldText: '0',
    soldCount: 0,
    totalCapacity: 500,
    status: 'REJECTED',
    details: {
      category: 'RELIGIOUS',
      description: 'Financial blessing seminar and wealth creation session.',
      formattedDate: 'Sat 01 Feb - 8:00 AM',
      venue: 'Main Bowl National Stadium',
      capacity: 500,
      agePolicy: 'None',
      refundPolicy: 'No refunds',
      bannerImage:
        'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-6',
        name: 'Faith Global',
        initials: 'FG',
        verified: false,
      },
      ticketTypes: [
        { id: 't-11', name: 'Delegate', price: 5000, quantity: 500 },
      ],
    },
  },
  {
    id: 'evt-8',
    title: 'Lagos fronted Meetup',
    slug: 'lagos-fronted-meetup',
    organizerName: 'Lagos Live Co.',
    organizerInitials: 'LP',
    type: 'FREE',
    soldText: '128/200',
    soldCount: 128,
    totalCapacity: 200,
    status: 'LIVE',
    details: {
      category: 'TECH',
      description: 'Monthly frontend engineering meetup focused on React, performance optimization, and modern UI engineering.',
      formattedDate: 'Sat 28 Feb - 11:00 AM',
      venue: 'CcHub, Yaba, Lagos',
      capacity: 200,
      agePolicy: 'Open to all',
      refundPolicy: 'Free event',
      bannerImage:
        'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1200&auto=format&fit=crop',
      organizer: {
        id: 'org-1',
        name: 'Lagos Live Co.',
        initials: 'LL',
        verified: true,
      },
      ticketTypes: [
        { id: 't-12', name: 'RSVP Ticket', price: 0, quantity: 200 },
      ],
    },
  },
];
